# 1. Numpy basics

In [21]:
import numpy as np
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(10,)

In [9]:
arr.size

10

In [22]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
array = [[1,2,3], [4,5,6], [7,8,9]]
type(array)

list

In [32]:
nparray = np.asarray([[1,2,3], [4,5,6], [7,8,9]])
#this can also be written as nparray = np.asarray(array)

In [31]:
type(nparray)

numpy.ndarray

In [2]:
import cv2
#here we read an image using imread and the second argument can be either 0 or 1 which means grayscale and BGR respectively
img = cv2.imread("gray.png", 0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
newimg = img + img
newimg

array([[118,  60, 208, 242,  30],
       [140, 250, 254, 254,  38],
       [162,  12, 254, 194, 108]], dtype=uint8)

In [9]:
#this will create a new image called newimg.png
cv2.imwrite("newimg.png", newimg)

True

In [10]:
img.shape

(3, 5)

In [11]:
newimg

array([[118,  60, 208, 242,  30],
       [140, 250, 254, 254,  38],
       [162,  12, 254, 194, 108]], dtype=uint8)

In [12]:
newimg[0:2]

array([[118,  60, 208, 242,  30],
       [140, 250, 254, 254,  38]], dtype=uint8)

In [13]:
newimg[0:2,0:2]

array([[118,  60],
       [140, 250]], dtype=uint8)

In [14]:
newimg[2,2]

254

In [15]:
for i in newimg:
    print(i)

[118  60 208 242  30]
[140 250 254 254  38]
[162  12 254 194 108]


In [16]:
newimg.flat

In [19]:
for i in newimg.flat:
    print(i)

118
60
208
242
30
140
250
254
254
38
162
12
254
194
108


In [23]:
imHstack = np.hstack((newimg,newimg))
imHstack

array([[118,  60, 208, 242,  30, 118,  60, 208, 242,  30],
       [140, 250, 254, 254,  38, 140, 250, 254, 254,  38],
       [162,  12, 254, 194, 108, 162,  12, 254, 194, 108]], dtype=uint8)

In [24]:
imVstack = np.vstack((newimg,newimg))
imVstack

array([[118,  60, 208, 242,  30],
       [140, 250, 254, 254,  38],
       [162,  12, 254, 194, 108],
       [118,  60, 208, 242,  30],
       [140, 250, 254, 254,  38],
       [162,  12, 254, 194, 108]], dtype=uint8)

In [27]:
imHsplit = np.hsplit(imHstack, 5)
imHsplit

[array([[118,  60],
        [140, 250],
        [162,  12]], dtype=uint8), array([[208, 242],
        [254, 254],
        [254, 194]], dtype=uint8), array([[ 30, 118],
        [ 38, 140],
        [108, 162]], dtype=uint8), array([[ 60, 208],
        [250, 254],
        [ 12, 254]], dtype=uint8), array([[242,  30],
        [254,  38],
        [194, 108]], dtype=uint8)]

In [28]:
imVsplit = np.vsplit(imVstack, 3)
imVsplit

[array([[118,  60, 208, 242,  30],
        [140, 250, 254, 254,  38]], dtype=uint8),
 array([[162,  12, 254, 194, 108],
        [118,  60, 208, 242,  30]], dtype=uint8),
 array([[140, 250, 254, 254,  38],
        [162,  12, 254, 194, 108]], dtype=uint8)]